#! /bin/sh -f

skipcheck=false

if $skipcheck || make Scripts.txt >&2
then	true
else	echo Could not acquire Unicode data file Scripts.txt >&2
	exit 1
fi
if $skipcheck || make Blocks.txt >&2
then	true
else	echo Could not acquire Unicode data file Blocks.txt >&2
	exit 1
fi

getranges () {
	egrep '^[^#]' Scripts.txt
	egrep "(Arrows|Mathematical Operators|Technical|Enclosed Alphanumerics|Pictographs|Control Pictures|Optical|Box Drawing|Miscellaneous.*Symbols|Block Elements|Geometric Shapes|Dingbats|Tiles|Cards|Emoticons|Transport|Alchemical|Chess)" Blocks.txt |
	sed -e "s,;.*, ; PictoSymbols,"
}

CC=${CC-cc}

(
cat <</eoc
#include <string.h>
#include <stdio.h>

long range_low;
long range_high = -2;
char * range_name = "";

void
flush ()
{
	if (range_high >= 0) {
		printf ("	{0x%04lX, 0x%04lX, 0, \"%s\"},\n", range_low, range_high, range_name);
	}
}

void
range (low, high, name)
	long low;
	long high;
	char * name;
{
	if (strcmp (name, "Common") == 0) {
		// ignore
	} else if (strcmp (name, range_name) == 0) {
		range_high = high;
	} else {
		flush ();
		range_low = low;
		range_high = high;
		range_name = name;
	}
}

int
main () {
/eoc


# transform
#00F8..01BA    ; Latin # L& [195] LATIN SMALL LETTER O WITH STROKE..LATIN SMALL LETTER EZH WITH TAIL
#01BB          ; Latin # Lo       LATIN LETTER TWO WITH STROKE

LC_ALL=C getranges |
sed	-e '/^#/ d' \
	-e 's/^\([0-9A-F][0-9A-F]*\)\.\.\([0-9A-F][0-9A-F]*\) *; *\([^ #]*\).*/\1	{0x\1, 0x\2, "\3"},/' \
	-e 's/^\([0-9A-F][0-9A-F]*\) *; *\([^ #]*\).*/\1	{0x\1, 0x\1, "\2"},/' \
	-e 's,^\(....\)	,00\1	,' \
	-e 's,^\(.....\)	,0\1	,' \
| sort | sed -e 's,^.*	,	,' -e 's,_, ,g' |
sed -e "s/{/range (/" -e "s/},/);/"


cat <</eoc
	flush ();
	return 0;
}
/eoc
) > mkscripts.tc

if $CC -o mkscripts.exe -x c mkscripts.tc
then	./mkscripts.exe > scripts.t
	rm -f mkscripts.tc mkscripts.exe
else	exit 1
fi
